version: "3.7"

services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skull_king
      MYSQL_USER: mermaid
      MYSQL_PASSWORD: beats_the_skull_king
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: mermaid
      PMA_PASSWORD: beats_the_skull_king